#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n============================="\
        "\n* Print a score distoribution and Cal standard diviation.\n"\
        "\n* Export standard diviation to a file whose name in inputted.\n"\
        "\n* Must check if fopen return value is NULL."\
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n Only cmopiling test."\
        "\n============================="

wget http://www.sic.shibaura-it.ac.jp/~sasano/lecture/enshu/19/1213kai/score.txt -P $PWD/

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc -lm "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile failed." \
            "\n============================="
    continue
  fi
  echo -e "tmp.dat\n" | $PWD/$filename
  if [ -f "$PWD/tmp.dat" ]; then
    echo -e "\n\nExported file is tmp.dat"
    tail "$PWD/tmp.dat"
    rm "$PWD/tmp.dat"
  else
    printf "\n\n$RED\n\n" " There isn't exported file tmp.dat"
  fi
  printf "%s\n" "$pad"
done

rm "$PWD/score.txt"

# NULL check
src=($PWD/$tfile*.c)
null_check src[@]

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

