#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo 10 80 38 60 90 | $PWD/$filename
  echo -e "expected\n" \
          "Ave       : 55.6\n" \
          "Over  Ave : 80 60 90\n" \
          "Under Ave : 10 38\n"
  echo 10 0 5 3 9 | $PWD/$filename
  echo -e "expected\n" \
          "Ave       : 5.4\n" \
          "Over  Ave : 10 9\n" \
          "Under Ave : 0 5 3\n"
  echo 200 90 85 83 89 90 | $PWD/$filename
  echo -e "expected\n" \
          "(if 200 included)\n" \
          "Ave       : 109.4\n" \
          "Over  Ave : 200\n" \
          "Under Ave : 90 85 83 89\n" \
          "  -------------------  \n" \
          "(if 200 not included)\n" \
          "Ave       : 87.4\n" \
          "Over  Ave : 90 89 90\n" \
          "Under Ave : 85 83\n"
  echo 60 59 61 0 0 | $PWD/$filename
  echo -e "expected\n" \
          "Ave       : 36.0\n" \
          "Over  Ave : 60 59 61\n" \
          "Under Ave : 0 0"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
