#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo 1 2 3 4 1 1 1 1 | $PWD/$filename      # => 3 3 7 7
  echo -e "expected 3 3 7 7\n"
  echo 2 -1 1 3 1 2 3 4 | $PWD/$filename     # => -1 0 10 14
  echo -e "expected -1 0 10 14\n"
  echo -5 -4 4 13 0 5 -3 9 | $PWD/$filename  # => 12 -61 -39 137
  echo -e "expected 12 -61 -39 137\n"
  echo -5 -4 4 13 0 0 0 0 | $PWD/$filename
  echo -e "expected 0 0 0 0"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
