#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Convert decimal to binary.\n" \
        "\n* Input is supposed to be 1 ~ 65535.\n" \
        "\n* Top output's top digit have to be 1." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n10" \
        "\n10000" \
        "\n70000 65535" \
        "\n19" \
        "\n0 1" \
        "\n2" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile failed." \
            "\n============================="
    continue
  fi
  echo -e "10\n" | $PWD/$filename
  echo -e "expected 1010\n"
  echo -e "10000\n" | $PWD/$filename
  echo -e "expected 10011100010000\n"
  echo -e "70000\n65535\n" | $PWD/$filename
  echo -e "expected (10001000101110000) 1111111111111111\n"
  echo -e "19\n" | $PWD/$filename
  echo -e "expected 10011\n"
  echo -e "0\n1\n" | $PWD/$filename
  echo -e "expected (0) 1\n"
  echo -e "2\n" | $PWD/$filename
  echo -e "expected 10"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile Check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

