#!/bin/sh
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Read file and get max height and weight." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n Only cmopiling test."\
        "\n============================="

# make data file which program reads
echo -e "\n=== Read file is ========="
echo -e "Taro   160.0 59.3"\
        "\nJiro   162.0 51.6"\
        "\nSaburo 182.0 76.5"\
        "\nShiro  170.0 60.7"
echo -e "=========================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  readfile=`extract_filename "$PWD/$cfile" "r"`
  echo -e "Read file is ${readfile}"
  echo -e "Taro   160.0 59.3"\
          "\nJiro   162.0 51.6"\
          "\nSaburo 182.0 76.5"\
          "\nShiro  170.0 60.7" | tee "$PWD/${readfile}"
  echo ""
  echo -e "\n" | $PWD/$filename
  echo -e " Expected: Mean height: 182.0cm"\
        "\n           Mean weight: 76.5kg"
  rm $PWD/${readfile}
  printf "%s\n" "$pad"
done

# NULL check
null_check $tfile

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

