#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

check(){
  file="$path/$1"
  string="$2"
  if [ -e $file ]; then
    printf "\n %s\n" "✓ File exits"
    in_file=`cat $file`
    if [ $string = $in_file ]; then
      printf " %s\n" "✓ Correct strings"
      rm $file
      return 0
    else
      wrong_input_string+=( $cfile )
      printf " $RED\n\n" "Wrong strings"
      rm $file
      return 1
    fi
  else
    wrong_file_name+=( $cfile )
    printf "\n $RED\n\n" "Wrong file name"
    return 2
  fi
  return 3
}

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm extra files
ex_file=`ls * | grep -Ev "*.c"`
n_ex_file=`ls -1 * 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_ex_file -gt 0 ]; then
  echo "-- removed --------------"
  echo $ex_file
  echo "-------------------------"
  rm $ex_file
fi

echo -e "\n============================="\
        "\n* Write input strings to file whose name is entered by user."\
        "\n* Input should be"\
        "\n    File name: ..."\
        "\n    Input string: ...\n"\
        "\n* Must check fopen is NULL"\
        "\n============================="

echo -e "\n==========Test case=========="\
        "\n fff abcde" \
        "\n asdasdasdasda a121$323$%&" \
        "\n a.txt a...\^-0\)\(\'\&\%\$\#\"\!\?\>\<\*\{\}_"\
        "\n=============================\n"

fail=()
wrong_file_name=()
wrong_input_string=()

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "fff\nabcde\n" | $PWD/$filename
  check "fff" "abcde"
  echo -e "asdasdasdasda\na121$323$%&\n" | $PWD/$filename
  check "asdasdasdasda" "a121$323$%&"
  echo -e "a.txt\na...\^-0\)\(\'\&\%\$\#\"\!\?\>\<\*\{\}_\n" | $PWD/$filename
  check "a.txt" "a...\^-0\)\(\'\&\%\$\#\"\!\?\>\<\*\{\}_"
  printf "%s\n" "$pad"
done

# NULL check
null_check $tfile

# print files which is not correct output
if [ ${#wrong_input_string[@]} -eq 0 -a ${#wrong_file_name[@]} -eq 0 ]; then
  printf "\n$pad\n"
  printf " $GREEN" "All files are correct output"
  printf "\n$pad\n"
else
  print_files wrong_input_string[@] "Wrong string"
  print_files wrong_file_name[@] "Wrong File name"
fi

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

