#!/bin/sh

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Cal area of a triangle.\n" \
        "\n  double area(point p1, point p2, point p3){ ... }\n" \
        "\n* Used structure is supposed to be\n" \
        "\n    typedef struct{" \
        "\n       double x;" \
        "\n       double y;" \
        "\n    } point\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 1.0 1.1 3.1 1.2 2.2 4.4" \
        "\n 0.0 0.0 2.0 2.0 4.0 4.0" \
        "\n -3 -5 -1 3 34 1" \
        "\n 9.7 6.9 7 4.5 3.2 0" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "1.0\n1.1\n3.1\n1.2\n2.2\n4.4\n" | $PWD/$filename
  echo -e " expected: 3.405\n"
  echo -e "0.0\n0.0\n2.0\n2.0\n4.0\n4.0\n" | $PWD/$filename
  echo -e " expected: 0\n"
  echo -e "-3\n-5\n-1\n3\n34\n1\n" | $PWD/$filename
  echo -e " expected: 142\n"
  echo -e "9.7\n6.9\n7\n4.5\n3.2\n0\n" | $PWD/$filename
  echo -e " expected: 1.515\n"
  echo -e "============================="
done

if [ ${#fail[@]} -gt 0 ]; then
  echo -e "\n\n========Failed files========="
  for failfile in ${fail[@]}; do
    echo ${failfile}
  done
  echo "============================="
fi

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
