#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Print students who are over criterion using structure.\n" \
        "\n* Student names include no spaces and" \
        "\n  inputs are supposed to be:" \
        "\n      char Student name " \
        "\n      int  Height(cm)" \
        "\n      int  criterion\n" \
        "\n* Structure is supposed to be\n" \
        "\n    typedef struct{" \
        "\n       char name[20];" \
        "\n       int height;" \
        "\n    } student\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n Taro 176 Jiro 165 Saburo 168 167" \
        "\n Taro 176 Jiro 165 Saburo 168 16" \
        "\n Taro 176 Jiro 165 Saburo 168 180" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "Taro\n176\nJiro\n165\nSaburo\n168\n167\n" | $PWD/$filename
  echo -e " expected: Taro, Saburo.\n"
  echo -e "Taro\n176\nJiro\n165\nSaburo\n168\n16\n" | $PWD/$filename
  echo -e " expected: Taro, Jiro, Saburo.\n"
  echo -e "Taro\n176\nJiro\n165\nSaburo\n168\n180\n" | $PWD/$filename
  echo -e " expected: No one is taller than criterion.\n"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

