#!/bin/sh

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Print 1 student BMI which entered student name using structure.\n" \
        "\n    void showBMI(student s){ ... }\n" \
        "\n* BMI is calculated by\n" \
        "\n    BMI = weight(kg) / height(m)^2\n" \
        "\n* Student names include no spaces and" \
        "\n  inputs are supposed to be\n" \
        "\n    char Student name " \
        "\n    int  Height" \
        "\n    int  Weight\n" \
        "\n* Structure is supposed to be\n" \
        "\n    typedef struct{" \
        "\n       char name[20];" \
        "\n       int height;" \
        "\n       int weight;" \
        "\n    } student\n" \
        "\n* You can use strcmp to compare 2 strings.\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro" \
        "\n Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro" \
        "\n Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro" \
        "\n Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro | $PWD/$filename
  echo -e " expected: Jiro, BMI is 20.385675.\n"
  echo Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro | $PWD/$filename
  echo -e " expected: Jiro, BMI is 20.385675.\n"
  echo Taro 176 64.5 Jiro 165 55.5 Saburo 168 70.0 Jiro | $PWD/$filename
  echo -e " expected: Jiro, BMI is 20.385675.\n"
  echo -e "============================="
done

if [ ${#fail[@]} -gt 0 ]; then
  echo -e "\n\n========Failed files========="
  for failfile in ${fail[@]}; do
    echo ${failfile}
  done
  echo "============================="
fi

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
