#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Print students who are over criterion using structure.\n" \
        "\n* Student names include no spaces and" \
        "\n  inputs are supposed to be\n" \
        "\n    char Student name " \
        "\n    int  Height(cm)" \
        "\n    int  criterion" \
        "\n* Structure is supposed to be\n" \
        "\n    typedef struct{" \
        "\n       char name[20];" \
        "\n       int height;" \
        "\n    } student\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n Taro 176 Jiro 165 Saburo 168 167" \
        "\n Taro 176 Jiro 165 Saburo 168 16" \
        "\n Taro 176 Jiro 165 Saburo 168 180" \
        "\n============================="

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo Taro 176 Jiro 165 Saburo 168 167 | $PWD/$filename
  echo -e " expected: Taro, Saburo.\n"
  echo Taro 176 Jiro 165 Saburo 168 16 | $PWD/$filename
  echo -e " expected: Taro, Jiro, Saburo.\n"
  echo Taro 176 Jiro 165 Saburo 168 180 | $PWD/$filename
  echo -e " expected: None is taller than criterion.\n"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
