#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Print 1 student info which entered student id using structure.\n" \
        "\n* Inputs are supposed to be\n" \
        "\n    int  Student ID" \
        "\n    char Student name " \
        "\n    int  English score\n" \
        "\n  Student name includes no spaces." \
        "\n* Structure is supposed to be\n" \
        "\n    struct{" \
        "\n       int id;" \
        "\n       char name[20];" \
        "\n       int english;" \
        "\n    }\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 10001 Taro 90 10002 Jiro 70 10003 Saburo 60 10002" \
        "\n 10 Ao 90 20 Shiro 70 30 Kiiro 60 20" \
        "\n 10 Taro 90 70 Jiro 70 30 Saburo 60 100" \
        "\n 10001 Taro 900 10002 Jiro 7000 10003 Saburo 360 10003" \
        "\n============================="

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo 10001 Taro 90 10002 Jiro 70 10003 Saburo 60 10002 | $PWD/$filename
  echo -e " expected: StudentID 10002, Name Jiro, English 70.\n"
  echo 10 Ao 90 20 Shiro 70 30 Kiiro 60 20 | $PWD/$filename
  echo -e " expected: StudentID 20, Name Shiro, English 70.\n"
  echo 10 Taro 90 Jiro 70 30 Saburo 60 100 | $PWD/$filename
  echo -e " expected: invalid student id.\n"
  echo 10001 Taro 900 10002 Jiro 7000 10003 Saburo 360 10003 | $PWD/$filename
  echo -e " expected: StudentID 10003, Name Saburo, English 360.\n"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
