#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

echo -e "\n=============================" \
        "\n* circumference function to calculate circumference. like\n" \
        "\n  double circumference (double radius) {...}\n" \
        "\n* Pi equeals 3.14" \
        "\n============================="

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo 3.5 | $PWD/$filename
  echo -e "expected 21.98\n"
  echo 0 5 | $PWD/$filename
  echo -e "expected 0 (31.4)\n"
  echo -1 90 | $PWD/$filename
  echo -e "expected (-6.28) 565.2"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
