#!/bin/sh

cd $(dirname $0)
cd ../../5han/

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo 5 10 1 6 3 1 7 10 1 5 5 -10 | $PWD/$filename
  echo -e "expected 54\n"
  echo 9 10 -1 | $PWD/$filename
  echo -e "expected 19\n"
  echo 45 10 1 10 45 -2 | $PWD/$filename
  echo -e "expected 111\n"
  echo 1 2 0 -2 | $PWD/$filename
  echo -e "expected 3\n"
  echo -e "\n============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

