#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Check if inputs are substring or not.\n" \
        "\n* Spaces and tabs aren't in inputs." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\ndef abcdefg" \
        "\ncef abcefg" \
        "\ncef abcdefg" \
        "\nabcefg acef" \
        "\nzvn abcdefg" \
        "\n============================="

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo def abcdefg | $PWD/$filename
  echo -e " expected: yes\n"
  echo cef abcefg | $PWD/$filename
  echo -e " expected: yes\n"
  echo cef abcdefg | $PWD/$filename
  echo -e " expected: no\n"
  echo abcefg acef | $PWD/$filename
  echo -e " expected: no\n"
  echo zvn abcdefg | $PWD/$filename
  echo -e " expected: no\n"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
