#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Counting words\n" \
        "\n* Let spaces, periods, commas be delimiter." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\nThis is a pen." \
        "\nIs this a pen?" \
        "\nHow are you? --- I'm fine, thank you." \
        "\nI think, that is 2 pen." \
        "\ninput" \
        "\nthirty-year-old" \
        "\n (no character)" \
        "\nth r y- e r-old" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "This is a pen.\n" | $PWD/$filename
  echo -e " expected: 4\n"
  echo -e "Is this a pen?\n" | $PWD/$filename
  echo -e " expected: 4\n"
  echo -e "How are you? --- I'm fine, thank you.\n" | $PWD/$filename
  echo -e " expected: 8\n"
  echo -e "I think, that is 2 pen.\n" | $PWD/$filename
  echo -e " expected: (6 if number is counted) 5\n"
  echo -e "input\n" | $PWD/$filename
  echo -e " expected: 1\n"
  echo -e "thirty-year-old\n" | $PWD/$filename
  echo -e " expected: 3\n"
  echo -e " \n" | $PWD/$filename
  echo -e " expected: 0\n"
  echo -e "th r y- e r-old\n" | $PWD/$filename
  echo -e " expected: 6\n"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

