#!/bin/sh

cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Picking up only capital letters and show them." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\nUnidentified Flying Object " \
        "\nABCD" \
        "\nAB-CD!" \
        "\nAB,CD." \
        "\nAB1CD?" \
        "\nAB 3 -  CD? ? " \
        "\n============================="

for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename"
  echo "Unidentified Flying Object" | $PWD/$filename
  echo -e " expected: UFO\n"
  echo "ABCD" | $PWD/$filename
  echo -e " expected: ABCD\n"
  echo "AB-CD!" | $PWD/$filename
  echo -e " expected: ABCD\n"
  echo "AB,CD." | $PWD/$filename
  echo -e " expected: ABCD\n"
  echo "AB1CD?" | $PWD/$filename
  echo -e " expected: ABCD\n"
  echo "\nAB 3 -  CD? ? " | $PWD/$filename
  echo -e " expected: ABCD\n"
  echo -e "============================="
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`

echo -e "\n========compile check========" \
        "\nSrc File      : $n_efile" \
        "\nExecute File  : $n_file" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
