#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Implement area(fig *fig) func which cal triangle or circle area.\n" \
        "\n  Pi is 3.14.\n" \
        "\n  typedef enum{Circle, Triangle}ct;\n" \
        "\n  typedef struct{" \
        "\n    ct ct;" \
        "\n    union{" \
        "\n      double radius;" \
        "\n      struct{" \
        "\n        double teihen;" \
        "\n        double takasa;" \
        "\n      }tri;" \
        "\n    }info;" \
        "\n  }fig;\n" \
        "\n  double area(fig *fig){ ... }\n" \
        "\n* 0 is circle, 1 is triangle." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 0 3.5" \
        "\n 0 0 (0.5)" \
        "\n 0 -4.5 (4)" \
        "\n 1 2.5 3.0" \
        "\n 1 2.7 4.0" \
        "\n 1 -4.5 2.0 (3.5)" \
        "\n 1 2.5 -3.0 (10)" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "0\n3.5\n" | $PWD/$filename
  echo -e " expected: 38.465\n"
  echo -e "0\n0\n0.5\n" | $PWD/$filename
  echo -e " expected: (invalid radius, radius must be positive, 0) 0.785\n"
  echo -e "0\n-4.5\n4\n" | $PWD/$filename
  echo -e " expected: (invalid radius, radius must be positive, 63.585) 50.24\n"
  echo -e "1\n2.5\n3.0\n" | $PWD/$filename
  echo -e " expected: 3.75\n"
  echo -e "1\n2.7\n4.0\n" | $PWD/$filename
  echo -e " expected: 5.4\n"
  echo -e "1\n-4.5\n2.0\n3.5\n" | $PWD/$filename
  echo -e " expected: (invalid base, base must be positive, -4.5) 3.5\n"
  echo -e "1\n2.5\n-3.0\n10" | $PWD/$filename
  echo -e " expected: (invalid height, height must be positive, -3.75) 12.5\n"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

