#!/bin/sh

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Counting words\n" \
        "\n* Use calloc to allocate a block of memory for char array.\n" \
        "\n* Let spaces, periods, commas be delimiter." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n100 This is a pen." \
        "\n100 Is this a pen?" \
        "\n100 How are you? --- I'm fine, thank you." \
        "\n100 I think, that is 2 pen." \
        "\n100 input" \
        "\n100 thirty-year-old" \
        "\n8 This is a pen." \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    # fail("${fail[@]}" $cfile)
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "100\nThis is a pen.\n" | $PWD/$filename
  echo -e " expected: 4\n"
  echo -e "100\nIs this a pen?\n" | $PWD/$filename
  echo -e " expected: 4\n"
  echo -e "100\nHow are you? --- I'm fine, thank you.\n" | $PWD/$filename
  echo -e " expected: 8\n"
  echo -e "100\nI think, that is 2 pen.\n" | $PWD/$filename
  echo -e " expected: (6 if number is counted) 5\n"
  echo -e "100\ninput\n" | $PWD/$filename
  echo -e " expected: 1\n"
  echo -e "100\nthirty-year-old\n" | $PWD/$filename
  echo -e " expected: 3\n"
  echo -e "8\nThis is a pen.\n" | $PWD/$filename
  echo -e " expected: 2(This is )\n"
  echo -e "============================="
done

if [ ${#fail[@]} -gt 0 ]; then
  echo -e "\n\n========Failed files========="
  for failfile in ${fail[@]}; do
    echo ${failfile}
  done
  echo "============================="
fi

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="
