#!/bin/sh

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-------- removed --------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Print reversed input (alphabet only).\n" \
        "\n* Max # of characters are specified by user input.\n" \
        "\n* Allocates a block of memory for char input using calloc. \n" \
        "\n* If input char length is more than max, program's behavior is up to students." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 10 abcde" \
        "\n 1000 input" \
        "\n 2 asdfg" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  echo -e "\n============================="
  echo "$filename"
  echo "----------------------------"
  # gcc "$PWD/$cfile" -o "$PWD/$filename" 2>/dev/null
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    # fail("${fail[@]}" $cfile)
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "10\nabcde\n" | $PWD/$filename
  echo -e " expected: edcba\n"
  echo -e "1000\ninput\n" | $PWD/$filename
  echo -e " expected: tupni\n"
  echo -e "2\nasdfg\n" | $PWD/$filename
  echo -e " expected: sa" \
          "\n(If this output is wrong, it's ok due to max char len.)\n"
  echo -e "============================="
done

if [ ${#fail[@]} -gt 0 ]; then
  echo -e "\n\n========Failed files========="
  for failfile in ${fail[@]}; do
    echo ${failfile}
  done
  echo "============================="
fi

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

