#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Inplement a func that sorts given int array.\n" \
        "\n  void sort(int *array, int size){ ... }\n" \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 10 50 38 80 60" \
        "\n 0 0 0 0 0" \
        "\n -1 -90 0 0 3" \
        "\n -10 -2 -100 -20 -4" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "10\n50\n38\n80\n60\n" | $PWD/$filename
  echo -e " expected: 80 60 50 38 10\n"
  echo -e "0\n0\n0\n0\n0\n" | $PWD/$filename
  echo -e " expected: 0 0 0 0 0\n"
  echo -e "-1\n-90\n0\n0\n3\n" | $PWD/$filename
  echo -e " expected: 3 0 0 -1 -90\n"
  echo -e "-10\n-2\n-100\n-20\n-4\n" | $PWD/$filename
  echo -e " expected: -2 -4 -10 -20 -100\n"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

