#!/bin/bash
. ../util.sh --source-only

shpath=$PWD
cd $(dirname $0)
path=${1:-../src}
cd $path

tfile=`basename $0`
n_file=`ls -1 $tfile*.c 2> /dev/null | wc -l`

if [ $n_file = 0 ]; then
  echo "There is no file starting with $tfile"
  exit 1
fi

# rm only exec files
efile=`ls $tfile* | grep -Ev "*.c"`
n_efile=`ls -1 $tfile* 2>/dev/null | grep -Ev "*.c" | wc -l`
if [ $n_efile -gt 0 ]; then
  echo "-- removed --------------"
  echo $efile
  echo "-------------------------"
  rm $efile
fi

echo -e "\n=============================" \
        "\n* Implement a func that cal inner product.\n" \
        "\n  double innerProd(double *array1, double *array2, int size){ ... }\n" \
        "\n* Passing first element pointer of array to the func" \
        "\n  and return the result as double type." \
        "\n============================="

echo -e "\n==========Test case==========" \
        "\n 1.1 1.2 1.3 2.1 2.2 2.3" \
        "\n 10 90 100 -1 -1 -1" \
        "\n -1 -4 12 0.1 3.2 5.6" \
        "\n -1 -4 -11 -3.1 -0.4 -0.01" \
        "\n============================="

fail=()
for cfile in $tfile*.c
do
  filename=`basename $cfile .c`
  printf "\n%s\n" "$pad"
  echo "$filename"
  printf "%s\n" "$line"
  gcc "$PWD/$cfile" -o "$PWD/$filename" 2>> $shpath/err.log
  if [ $? -ne 0 ]; then
    fail+=( $cfile )
    echo -e "Compile filed." \
            "\n============================="
    continue
  fi
  echo -e "1.1\n1.2\n1.3\n2.1\n2.2\n2.3\n" | $PWD/$filename
  echo -e " expected: 7.94\n"
  echo -e "10\n90\n100\n-1\n-1\n-1\n" | $PWD/$filename
  echo -e " expected: -200\n"
  echo -e "-1\n-4\n12\n0.1\n3.2\n5.6\n" | $PWD/$filename
  echo -e " expected: 54.3\n"
  echo -e "-1\n-4\n-11\n-3.1\n-0.4\n-0.01\n" | $PWD/$filename
  echo -e " expected: 4.81\n"
  printf "%s\n" "$pad"
done

n_efile=`ls $tfile* | grep -Ev "*.c" | wc -l`
echo -e "\n========Compile check========" \
        "\nSrc File      : $n_file" \
        "\nExecute File  : $n_efile" \
        "\nCompile Error : $(($n_file-$n_efile))" \
        "\n============================="

print_files fail[@] "Failed files"

